import Providers from '@/hooks/providers';
import '@/styles/globals.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import { FooterSlot, HeaderSlot } from '@/components/layout';

config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Experiences | Contentful',
  description: 'Generated by Contentful Experiences.',
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}): React.JSX.Element => {
  return (
    <html lang='en'>
      <Providers>
        <body
          className={`flex flex-col h-full items-center justify-center min-h-svh ${inter.className}`}
        >
          <header className='bg-black sticky text-white top-0 w-full z-50'>
            <HeaderSlot />
          </header>
          <main className='grow h-full mb-auto min-h-[48rem] w-full'>
            {children}
          </main>
          <footer className='bg-black mt-4 pt-4 text-white w-full'>
            <FooterSlot />
          </footer>
        </body>
      </Providers>
    </html>
  );
};

export default RootLayout;
