import {
  faDhl,
  faDiscord,
  faFacebook,
  faFacebookSquare,
  faFedex,
  faGithub,
  faInstagram,
  faLinkedin,
  faPinterest,
  faTiktok,
  faTwitter,
  faTwitterSquare,
  faUps,
  faUsps,
  faXTwitter,
  faYoutube,
  IconDefinition,
} from '@fortawesome/free-brands-svg-icons';
import {
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faAngleDown,
  faAngleUp,
  faArrowRight,
  faBars,
  faBookOpen,
  faBorderAll,
  faBoxesStacked,
  faChartArea,
  faChartBar,
  faChartLine,
  faChartPie,
  faClipboard,
  faCog,
  faComments,
  faCompass,
  faDesktop,
  faDolly,
  faDotCircle,
  faEdit,
  faEnvelope,
  faEnvelopeSquare,
  faExclamationCircle,
  faFileInvoice,
  faFileInvoiceDollar,
  faFilePdf,
  faFileSignature,
  faGlobe,
  faHouse,
  faInbox,
  faInfoCircle,
  faLifeRing,
  faMap,
  faNewspaper,
  faPallet,
  faPoll,
  faPollH,
  faPowerOff,
  faSearch,
  faShop,
  faSignOut,
  faSignOutAlt,
  faStoreAlt,
  faTag,
  faTrash,
  faTruck,
  faUpRightFromSquare,
  faUserCircle,
  faUserGear,
  faUsers,
  faWarehouse,
  faX,
} from '@fortawesome/free-solid-svg-icons';

const ICONS: Record<string, IconDefinition> = {
  'angle-double-left': faAngleDoubleLeft,
  'angle-double-right': faAngleDoubleRight,
  'angle-down': faAngleDown,
  'angle-up': faAngleUp,
  'arrow-right': faArrowRight,
  'arrow-up-right-from-square': faUpRightFromSquare,
  bars: faBars,
  'book-open': faBookOpen,
  'border-all': faBorderAll,
  'boxes-stacked': faBoxesStacked,
  'chart-area': faChartArea,
  'chart-bar': faChartBar,
  'chart-line': faChartLine,
  'chart-pie': faChartPie,
  clipboard: faClipboard,
  cog: faCog,
  comments: faComments,
  compass: faCompass,
  desktop: faDesktop,
  dhl: faDhl,
  discord: faDiscord,
  dolly: faDolly,
  'dot-circle': faDotCircle,
  edit: faEdit,
  envelope: faEnvelope,
  'envelope-square': faEnvelopeSquare,
  'exclamation-circle': faExclamationCircle,
  facebook: faFacebook,
  'facebook-square': faFacebookSquare,
  fedex: faFedex,
  'file-invoice': faFileInvoice,
  'file-invoice-dollar': faFileInvoiceDollar,
  'file-pdf': faFilePdf,
  'file-signature': faFileSignature,
  github: faGithub,
  globe: faGlobe,
  house: faHouse,
  inbox: faInbox,
  'info-circle': faInfoCircle,
  instagram: faInstagram,
  'life-ring': faLifeRing,
  linkedin: faLinkedin,
  map: faMap,
  newspaper: faNewspaper,
  pallet: faPallet,
  pinterest: faPinterest,
  poll: faPoll,
  'poll-h': faPollH,
  'power-off': faPowerOff,
  search: faSearch,
  shop: faShop,
  'sign-out': faSignOut,
  'sign-out-alt': faSignOutAlt,
  'store-alt': faStoreAlt,
  tag: faTag,
  tiktok: faTiktok,
  trash: faTrash,
  truck: faTruck,
  twitter: faTwitter,
  'twitter-square': faTwitterSquare,
  'twitter-x': faXTwitter,
  ups: faUps,
  'user-circle': faUserCircle,
  'user-gear': faUserGear,
  users: faUsers,
  usps: faUsps,
  warehouse: faWarehouse,
  x: faX,
  'x-twitter': faXTwitter,
  youtube: faYoutube,
};

export default ICONS;
